### ISSUE TITLE
Option to use relative URLs

### ISSUE THREAD

**Issue by ind1go** [gjtorikian/graphql-docs#51]
Have you considered the ability to be able to generate with relative URLs rather than a known root?

We deploy to multiple different environments and the base URL changes between those. We'd like to just build once for all environments.

I don't know whether this is already possible through customising the layouts and overriding `templates`, but I'm not sure how - whether there's some context variable that html-pipeline carries around to determine how deep the current HTML file is nested. If you've got insight here, I'd love to hear that.

**Comment by gjtorikian** [comment]
Heya! I definitely wouldn't be opposed to adding an option for this, but I am a bit confused about the problem. 😅 

There is an option called `base_url` which lets you set a `base_url`. If you do two builds -- one per environment -- and change the `base_url` each time, would that solve the problem?

**Comment by ind1go** [comment]
Yeah, we just want to build once and pull that from an artifact repository multiple times, though. We're not always in control of who's pulling it and to where.

I think I've got a way round this in #56 which allows me to do the hard work in a pipeline plugin and in some logic in the `sidebar.html` and `default.html`, by purely adding a single new context variable to this library - so no new options required. Let me know how you feel about that.

_Apparently I broke most of the tests, although only on Travis, not locally... working on that!_

**Comment by bbugh** [comment]
@gjtorikian to explain the issue more broadly, the docs currently generate absolute paths (`/assets/styles.css`). This breaks both local previews, and server deployment in a subdirectory. It would be nice for our devs to be able to preview their generated docs without having to start a local server to do so, and for us to deploy the docs wherever we want without caring about the absolute url. Generating relative paths (`assets/styles.css`, `../../index.html`) instead of absolute paths would solve the local preview and the subdirectory deployment issue.

@ind1go could you explain briefly what your solution was? I looked at #56 and I'm not sure how you could use that to generate relative urls.

Thank you! This is a great library.

**Comment by ind1go** [comment]
Sure, I'm using a combination of a custom html-pipeline filter and some extra ERB tags in the templates which just about work. A gist containing them is at https://gist.github.com/ind1go/3e1e523602987893f86059784df26521.

 In particular, my overridden default.html and sidebar.html needed the ERB tags. I've only shown default.html as sidebar.html was very similar.

I don't do Ruby so I imagine there's a much neater way of doing it, but this works for me!
