### ISSUE TITLE
Output of queries is missing

### ISSUE THREAD

**Issue by bernardo-martinez** [gjtorikian/graphql-docs#74]
The output of `mutations` is generated under: `mutation/mutationName/index.html`, but all the `query/queryName` are missing. 

It only generates `/operation/query/index.html` which is about the root query type.

**Comment by gjtorikian** [comment]
I think this issue is the same as @stephentuso 's https://github.com/gjtorikian/graphql-docs/issues/46#issuecomment-529660484

Because mutations have input and output fields--where are different than what a root query has--the items are split up and presented in the sidebar.

Happy to hear alternative ways to present this information.

**Comment by bernardo-martinez** [comment]
I think it would make sense to have Queries under their own sidebar section, because Queries can have inputs too (input arguments) and obviously outputs.

I have a lot of named Queries with input arguments, which get no page generated, so in consistency with mutations I would suggest to add them so. I would be happy to help if needed.
