### ISSUE TITLE
Support class based GraphQL

### ISSUE THREAD

**Issue by JanStevens** [gjtorikian/graphql-docs#79]
Hello,

Is this gem compatible with class based definitions? I attempted to use it but I quickly ran into issues. In the parser I see things like

```ruby
if schema.is_a?(GraphQL::Schema)
```

Regards,

**Comment by gjtorikian** [comment]
Nope, sorry -- you need to provide a string of the IDL (or a file path pointing to it on disk), rather than the pure Ruby class names. If you're using `graphql-ruby` though this should be easy to create from the existing class-based schema.

**Comment by JanStevens** [comment]
Ok got so far but now I hit an error

```ruby
     options = GraphQLDocs::Configuration::GRAPHQLDOCS_DEFAULTS.merge({})
      idl = ::CrewSchema.to_definition(context: { current_user: pundit_user })
      parser = GraphQLDocs::Parser.new(idl, options)
      parsed_schema = parser.parse

      generator = GraphQLDocs::Generator.new(parsed_schema, options)

      docs = generator.generate
```

```
TypeError - I'm not sure what Class is!:
```

After debugging it seems that graphql-docs doesnt support `GraphQL::Types::Boolean`?

**Comment by gjtorikian** [comment]
It does, and is even tested for it:

https://github.com/gjtorikian/graphql-docs/blob/3741b0f2798bbeae8f430069c363834853d936c4/test/graphql-docs/fixtures/gh-schema.graphql#L357

**Comment by JanStevens** [comment]
Then why does it fail at the parser?

https://github.com/gjtorikian/graphql-docs/blob/56cba3a11e6854687a393073811c639e32f65a31/lib/graphql-docs/parser.rb#L48-L133

Here I don't see any reference to `GraphQL::Types::Boolean` and thats the line that fails

**Comment by gjtorikian** [comment]
Can you share your whole IDL file here?

**Comment by JanStevens** [comment]
> Can you share your whole IDL file here?

Nope sorry that will be a bit to big. What the author of graphql-ruby told me is that from graphql-ruby 1.10, graphql-ruby makes a class-based schema when parsing from string.

For moving forward, I started a MR where I just upgraded the gem dependencies to use latest 1.10 version, as you can see graphql-docs is not compatible with latest graphql-ruby. https://github.com/gjtorikian/graphql-docs/pull/80

Maybe for now we can pin the version until support for 1.10 is added?

**Comment by gjtorikian** [comment]
@rmosolgo The changes mentioned here _super_ broke the gem, including surprising breakages like not being able to call methods:

```
NoMethodError: undefined method `connection?' for #<GraphQL::Schema::Argument:0x00007fc3b5b0e980>
    /Users/gjtorikian/Development/graphql-docs/lib/graphql-docs/parser.rb:195:in `block in fetch_fields'
    /Users/gjtorikian/Development/graphql-docs/lib/graphql-docs/parser.rb:168:in `each_value'
    /Users/gjtorikian/Development/graphql-docs/lib/graphql-docs/parser.rb:168:in `fetch_fields'
    /Users/gjtorikian/Development/graphql-docs/lib/graphql-docs/parser.rb:121:in `block in parse'
    /Users/gjtorikian/Development/graphql-docs/lib/graphql-docs/parser.rb:43:in `each_value'
    /Users/gjtorikian/Development/graphql-docs/lib/graphql-docs/parser.rb:43:in `parse'
    /Users/gjtorikian/Development/graphql-docs/test/graphql-docs/generator_test.rb:22:in `setup'
```

Is there a change list or PR I can review to get this gem more compatible with the newest release?

**Comment by rmosolgo** [comment]
👋 Hey, the main change is that `Schema.from_definition` used to return a legacy-style Schema instance, but now it builds a Schema _class_, just like the Ruby DSL ([changelog](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1100-20-jan-2020)). (This is part of the gem's shift from `.define`-based definitions to `class ...`-based definitions, underway since early 2018 😅)

Especially since 1.10.0, which uses _only_ classes is most cases, gems have needed updates to remain compatible. Here are some other examples: 

- https://github.com/github/graphql-client/pull/222
- https://github.com/github/graphql-relay-walker/pull/17
- https://github.com/Shopify/graphql-batch/pull/116
- https://github.com/xuorig/graphql-schema_comparator/pull/29

I'm afraid there's _not_ a specific guide for updating tools, but general migration info is here: https://graphql-ruby.org/schema/class_based_api.html

**Comment by gjtorikian** [comment]
Thanks for those sample links, @rmosolgo, that helped!
